/**
 * @file Automatically generated by barrelsby.
 */

 export * from './createMultiHighlightPlugin';
 export * from './defaults';
 export * from './getMultiHighlightDeserialize';
 export * from './transforms';
 export * from './queries';
 